### ISSUE TITLE
The chest is gone when it changes the world [®]

### ISSUE THREAD

**Issue by hachkingtohach1** [Hydreon/Steadfast2#258] opened 2017-07-27 01:15 UTC
Chests were placed in another world, when I returned to the world it was turned into invisible.

**Comment by BI0MER** [comment] 2017-07-27 01:29
duplicate #256, it problem with tiles

**Comment by hachkingtohach1** [comment] 2017-07-27 01:32
How do I fix it?

**Comment by BI0MER** [comment] 2017-07-27 01:38
I'll try to fix this (if the developers do not respond)

**Comment by hachkingtohach1** [comment] 2017-07-27 01:40
Thank you for the help

**Comment by vchibikov** [comment] 2017-07-27 05:19
We will check this

**Comment by vchibikov** [comment] 2017-07-27 06:09
@hachkingtohach1  Could not reproduce. What is your map's format? Are you using any plugin? Did you have this bug without any plugins? May you give me your map? What is your client version?

**Comment by hachkingtohach1** [comment] 2017-07-27 06:14
Plugin my /INFO]: PlChatLogin v1.4, ClearLagg v1.1.0, CustomRanks v1.0.0,
DevTools v1.10.0, Donate v3, EconomyAPI v2.0.9, HungerGamesHyplex vBest,
KitsDoDo v1.0.0 beta, LBParticles-Tim_15 v0.0.1, ManyWorlds v2.1.0, NPC v1.4
, Pets v1.0.0, RealTime v2.1.1, ServerAuth vHyplex, TapToDo-LEET.CC v1.0.0,
aFloatingText v1.2, iProtector v3.1b, Lobby-by-DPMC v1, BanClient v1.1,
BuyFly_MCPE14 v1, TeamsDoDo v2.0.0
World default
Vào 27-07-2017 13:09, "Victor Chibikov" <notifications@github.com> đã viết:

@hachkingtohach1 <https://github.com/hachkingtohach1> Could not reproduce.
What is your map's format? Are you using any plugin? Did you have this bug
without any plugins? May you give me your map? What is your client version?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Hydreon/Steadfast2/issues/258#issuecomment-318268118>,
or mute the thread

**Comment by MrSmileCH** [comment] 2017-07-27 20:43
@hachkingtohach1 
Hi, I have seen that in your plugins you have a login plugin you could provide the download link I would appreciate it very much, I have been looking for and I have not found any that works for me

**Comment by BI0MER** [comment] 2017-07-28 07:01
Fixed in https://github.com/Hydreon/Steadfast2/commit/c39e7fb7adcdb32896e884b53164b2b59fb9106b, thank you all for your help

**Closed** 2017-07-28 08:40 UTC
