### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by RompeCraneos** [Hydreon/Steadfast2#350] opened 2017-09-03 16:53 UTC
Cant put armor from my inventory or get items from chest, i tested in win10 and mcpe version 1.1.5

**Comment by vchibikov** [comment] 2017-09-04 04:27
Armor works fine for me, chests also not cause troubles. Do you have this problems on vanilla Steadfast or you use some plugins?

**Comment by RompeCraneos** [comment] 2017-09-04 21:02
using plugins, armor is good yes.. the problem is chest, no problems when im alone, but in my server with people this occurs a lot in skywars, sometimes no, but almost ever

**Comment by vchibikov** [comment] 2017-09-05 05:17
Try reproduce it without plugins, with two devices. Or tell us how to reproduce it.

**Comment by akaSnapy** [comment] 2017-09-10 18:43
@vchibikov I think he uses 1.1 versions, where the Classic aka PC gui is broken and fixed on 1.2

**Comment by TheRoyalBlock** [comment] 2017-09-10 19:57
oh

**Comment by RompeCraneos** [comment] 2017-09-10 20:36
Yes, some solution or fix?

**Comment by TheRoyalBlock** [comment] 2017-09-10 22:50
All softwares have had numerous problems with the pre-1.2 windows 10 edition ui. I have not personally found a solution, nor have my other coding friends, but I believe someone else certainly has...

**Comment by GiantQuartz** [comment] 2017-09-19 13:16
@TheRoyalBlock All UI bugs were client-sided, they were fixed in the latest Minecraft 1.2 build.

**Comment by TheRoyalBlock** [comment] 2017-09-19 19:24
yes, that's what I just pointed out. Minecraft 1.2 fixed it, but when connecting with older clients the UI is messed up. that's what the problem is

**Comment by TheRoyalBlock** [comment] 2017-09-22 23:05
As @vchibikov pointed out in another issue, pre-1.2 support will be cut in a few days/weeks. Therefore, there is no point in fixing old inventories if the work will be irrelevant soon.

*Close this*

**Closed** 2017-09-26 23:24 UTC
