### ISSUE TITLE
Signs disappear

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#256] opened 2017-07-25 17:15 UTC
https://youtu.be/6yhY6rI5E1M

**Comment by xZeroMCPE** [comment] 2017-07-26 04:20
You can self-fix this by placing a sign/tile on a task.

**Comment by MrSmileCH** [comment] 2017-07-26 04:49
This did not happen to me in the ancestor build

**Comment by BI0MER** [comment] 2017-07-27 00:53
It did not happen after the reuploaded (reinstallation) the world?

**Comment by BI0MER** [comment] 2017-07-27 01:36
After installing the world with tiles, they become invisible until they are broken with the canceled BlockBreakEvent

**Comment by vchibikov** [comment] 2017-07-27 05:55
Could not reproduce. What is your map's format? Are you using any plugin? Did you have this bug without any plugins? May you give me your map?

**Comment by BI0MER** [comment] 2017-07-27 08:48
@vchibikov place chests and sign in the world that you loaded manually, restart the server and load it, the chests and sign in it will become invisible

**Comment by BI0MER** [comment] 2017-07-27 09:35
@vchibikov They become invisible NOT when the reload world with the server starting and server stopping (for reproduce - reload world manually)

**Comment by BI0MER** [comment] 2017-07-28 04:03
I can not find the reason (the beds also become invisible, but I saw this bug on the MiNET). Maybe this is a bug version?

**Comment by BI0MER** [comment] 2017-07-28 05:50
@vchibikov Maybe I found a bug with tiles, will you help me?
[05:37:44] [Server thread/CRITICAL]: Could not tick level bedwarsone: Invalid Ch                                                                                                                                                             unk sent
[05:37:44] [Server thread/CRITICAL]: pocketmine\utils\ChunkException: "Invalid C                                                                                                                                                             hunk sent" (EXCEPTION) in "/src/pocketmine/level/format/mcregion/McRegion" at li                                                                                                                                                             ne 116
[05:37:44] [Server thread/DEBUG]: #0 /src/pocketmine/level/Level(658): pocketmin                                                                                                                                                             e\level\Level->processChunkRequest(boolean)
[05:37:44] [Server thread/DEBUG]: #1 /src/pocketmine/Server(2368): pocketmine\le                                                                                                                                                             vel\Level->doTick(integer 1500)
[05:37:44] [Server thread/DEBUG]: #2 /src/pocketmine/Server(2512): pocketmine\Se                                                                                                                                                             rver->checkTickUpdates(integer 1500)
[05:37:44] [Server thread/DEBUG]: #3 /src/pocketmine/Server(2264): pocketmine\Se                                                                                                                                                             rver->tick(boolean)
[05:37:44] [Server thread/DEBUG]: #4 /src/pocketmine/Server(2138): pocketmine\Se                                                                                                                                                             rver->tickProcessor(boolean)
[05:37:44] [Server thread/DEBUG]: #5 /src/pocketmine/Server(1754): pocketmine\Se                                                                                                                                                             rver->start(boolean)
[05:37:44] [Server thread/DEBUG]: #6 /src/pocketmine/PocketMine(459): pocketmine                                                                                                                                                             \Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\M                                                                                                                                                             ainLogger object, string /root/minigame/, string /root/minigame/, string /root/m                                                                                                                                                             inigame/plugins/)

**Comment by BI0MER** [comment] 2017-07-28 06:59
Yea, it's fixed in https://github.com/Hydreon/Steadfast2/commit/c39e7fb7adcdb32896e884b53164b2b59fb9106b. Thank you (and me (if you agree, please +1) :D)

**Comment by MrSmileCH** [comment] 2017-07-28 08:08
Signs no longer disappear?

**Closed** 2017-07-28 08:41 UTC

**Comment by BI0MER** [comment] 2017-07-28 09:37
@MrSmileCH No, it's fixed

**Comment by MrSmileCH** [comment] 2017-07-28 17:04
thanks :D
