### ISSUE TITLE
why do I have an empty world.

### ISSUE THREAD

**Issue by flayzer** [Hydreon/Steadfast2#343] opened 2017-08-31 15:31 UTC
why do I have an empty world. Completely new core, and after the entrance an empty world?

**Comment by SuperMaXAleX** [comment] 2017-08-31 15:47
Duplicate of #248, #266, #278, #288

**Comment by vchibikov** [comment] 2017-09-01 03:48
File server.properties set auto-generate value as on

**Closed by vchibikov** 2017-09-01 03:48 UTC
