### ISSUE TITLE
bug number online player?

### ISSUE THREAD

**Issue by MrSmileCH** [Hydreon/Steadfast2#368] opened 2017-09-11 23:21 UTC
![sin titulo1](https://user-images.githubusercontent.com/27845246/30301113-466dbd86-971e-11e7-869f-0f556039845a.png)

![sin titulo](https://user-images.githubusercontent.com/27845246/30301043-bf27170a-971d-11e7-9da0-fc8ce164edc7.png)
does not display the number of online players

**Comment by vchibikov** [comment] 2017-09-14 11:49
Couldn't reproduce. Do you use QueryRegenerateEvent in your plugins? What client version do you use?

**Comment by MrSmileCH** [comment] 2017-09-16 01:52
no friend, I have done it without plugins and it happens to me the same, I use the most recent versions that you get every 24 hours

**Comment by TheRoyalBlock** [comment] 2017-09-22 23:03
I cannot reproduce either. This is not the software's fault. Either: bad client, or bad plugin. 

*Close this*

**Closed** 2017-09-26 23:23 UTC
